### ISSUE TITLE
Old 3DS failed downgrading from 9.2.0 to 2.1.0

### ISSUE THREAD

**Issue by xuefer** [Plailect/PlaiSysUpdater#11]
PlaiSysUpdater crash downgrading from 9.2.0 to 2.1.0 when updating specified title, but sorry i had the log removed because I've manage to downgrade to 2.1.0 after upgrading to 11.x

in the Guide, the upgrade seems not required. at least you state that each part of guide can be done separately and "Part 5 - arm9loaderhax" never said about requiring  >9.2.0 (or != 9.2.0) before downgrade. although in "Part 2 - 9.2.0 Downgrade" it recommend upgrading to latest for EmuNand

either PlaiSysUpdater or just he home menu is crashing. the crash happens when downgrading home menu title
https://gbatemp.net/threads/crash-when-downgrading-a9lh.421004/
https://www.reddit.com/r/3dshacks/comments/4hwt70/full_arm9loaderhax_cfw_guide_everything_you_need/d2zjmld

**Comment by Plailect** [comment]
The guide says that they can be done separately, but that applies to what the Get Started page directs people to. You can't literally just pick whatever you want to do and expect it to work. 

Part 5 doesn't say anything about requiring >9.2.0 before downgrading because Part 5 is totally unrelated to downgrading...

The issue with downgrading on the home menu CIA on 9.2.0 is known, and that's why the instructions have users update to latest on RedNAND first.
